"""Backward-compatible re-exports. New code should import from the specific module."""

from gotg.session_types import (  # noqa: F401
    SessionSetupError,
    PhaseAdvanceError,
    ReviewError,
    ResolutionStrategy,
    BranchReview,
    ReviewResult,
    MergeResult,
    NextLayerResult,
    AdvanceResult,
    ConflictFileInfo,
    ConflictInfo,
    AiResolutionResult,
    SessionInfra,
    SessionSetup,
    ContinueContext,
    resolve_layer,
)
from gotg.session_setup import (  # noqa: F401
    build_session_infra,
    prepare_session,
    prepare_grooming_session,
    prepare_continue,
    run_and_persist,
    persist_event,
    validate_iteration_for_run,
    build_file_infra,
    setup_worktrees,
    apply_and_inject,
    load_diffs_for_review,
)
from gotg.session_advance import (  # noqa: F401
    validate_advance,
    advance_phase,
    validate_next_layer,
    advance_next_layer,
)
from gotg.session_review import (  # noqa: F401
    load_review_branches,
    merge_branches,
    load_conflict_info,
    resolve_conflict_file,
    ai_resolve_conflict,
    finalize_merge,
)

__all__ = [
    # Types
    "SessionSetupError",
    "PhaseAdvanceError",
    "ReviewError",
    "ResolutionStrategy",
    "BranchReview",
    "ReviewResult",
    "MergeResult",
    "NextLayerResult",
    "AdvanceResult",
    "ConflictFileInfo",
    "ConflictInfo",
    "AiResolutionResult",
    "SessionInfra",
    "SessionSetup",
    "ContinueContext",
    "resolve_layer",
    # Setup
    "build_session_infra",
    "prepare_session",
    "prepare_grooming_session",
    "prepare_continue",
    "run_and_persist",
    "persist_event",
    "validate_iteration_for_run",
    "build_file_infra",
    "setup_worktrees",
    "apply_and_inject",
    "load_diffs_for_review",
    # Advance
    "validate_advance",
    "advance_phase",
    "validate_next_layer",
    "advance_next_layer",
    # Review
    "load_review_branches",
    "merge_branches",
    "load_conflict_info",
    "resolve_conflict_file",
    "ai_resolve_conflict",
    "finalize_merge",
]
